name: Push

on:
  push:
    branches:
      - master
      - main

env:
  REPOSITORY_HOST: github.com
  REPOSITORY_OWNER: EpitechIT2020
  REPOSITORY_NAME: G-JAM-001-TLS-0-1-jam-lucas.arsene

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Build"
        run: |
          docker build . -f Dockerfile

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ env.REPOSITORY_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push
        run: |
          git push git@$REPOSITORY_HOST:/$REPOSITORY_OWNER/$REPOSITORY_NAME --force
